version: '3.1'

services:
  db:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data

volumes:
  db: {}
  redis: {} 
