# Generated by Django 4.1.6 on 2023-03-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carriers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('hasReadAccessToAll', models.BooleanField(default=False)),
                ('hasWriteAccessToAll', models.BooleanField(default=False)),
                ('hasReadAccessTo', models.ManyToManyField(blank=True, default=None, related_name='hasReadAccessTo', to='carriers.carrier')),
                ('hasWriteAccessTo', models.ManyToManyField(blank=True, default=None, related_name='hasWriteAccessTo', to='carriers.carrier')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('edmc', 'EDMC'), ('discord', 'Discord'), ('admin', 'Admin'), ('other', 'Other')], default='other', max_length=20)),
                ('discorduser', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('oldValue', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('newValue', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.carrier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apikey')),
            ],
        ),
    ]
