# Generated by Django 4.0.5 on 2022-06-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_alter_carrier_callsign_alter_carrier_departuretime_and_more'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='hasAccessTo',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='carriers.carrier'),
        ),
    ]
