# Generated by Django 4.0.5 on 2022-06-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apikey_hasaccessto'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='hasAccessToAll',
            field=models.BooleanField(default=False),
        ),
    ]
