# Generated by Django 4.0.5 on 2022-06-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_alter_carrier_callsign_alter_carrier_departuretime_and_more'),
        ('api', '0004_apikey_hasaccesstoall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='hasAccessToAll',
            new_name='hasWriteAccessToAll',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='hasAccessTo',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='hasWriteAccess',
        ),
        migrations.AddField(
            model_name='apikey',
            name='hasReadAccessTo',
            field=models.ManyToManyField(blank=True, default=None, related_name='hasReadAccessTo', to='carriers.carrier'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='hasReadAccessToAll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikey',
            name='hasWriteAccessTo',
            field=models.ManyToManyField(blank=True, default=None, related_name='hasWriteAccessTo', to='carriers.carrier'),
        ),
    ]
