# Generated by Django 4.1.6 on 2023-02-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_apilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='discorduser',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
