# Generated by Django 4.1.6 on 2023-03-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_apilog_discorduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apikey'),
        ),
    ]
