# Generated by Django 4.1.6 on 2023-06-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduserdata',
            name='discriminator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discorduserdata',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
