# Generated by Django 4.1.6 on 2023-06-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_discorduserdata_discriminator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carrier_management_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
