# Generated by Django 4.1.6 on 2023-06-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_carrier_management_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.discorduserdata'),
        ),
    ]
