# Generated by Django 4.1.6 on 2023-06-01 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('odyssey', models.BooleanField(default=False)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('callsign', models.CharField(max_length=255, unique=True)),
                ('currentLocation', models.CharField(max_length=255)),
                ('previousLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('dockingAccess', models.CharField(choices=[('all', 'All'), ('none', 'None'), ('friends', 'Friends'), ('squadron', 'Squadron'), ('squadronfriends', 'Squadron & Friends')], default='all', max_length=255)),
                ('allowNotorious', models.BooleanField(default=False)),
                ('fuelLevel', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('cargoUsedSpace', models.IntegerField(default=0)),
                ('cargoFreeSpace', models.IntegerField(default=0)),
                ('balance', models.BigIntegerField(default=0)),
                ('reserveBalance', models.BigIntegerField(default=0)),
                ('availableBalance', models.BigIntegerField(default=0)),
                ('owner', models.CharField(max_length=255)),
                ('ownerDiscordID', models.BigIntegerField(blank=True, null=True)),
                ('imageURL', models.URLField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('flagship', 'Flagship'), ('freighter', 'Freighter'), ('supportvessel', 'Support Vessel'), ('other', 'Other')], default='other', max_length=255)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(blank=True, to='carriers.carrierservice')),
            ],
        ),
    ]
