# Generated by Django 4.0.5 on 2022-06-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0002_remove_carrierservice_taxation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='callsign',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='departureTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='nextDestination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='nextDestinationTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='nextLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
