# Generated by Django 4.0.5 on 2023-01-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_alter_carrier_callsign_alter_carrier_departuretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
