# Generated by Django 4.1.6 on 2023-03-28 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_alter_carrier_ownerdiscordid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='allowNotorious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrier',
            name='availableBalance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrier',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrier',
            name='cargoFreeSpace',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrier',
            name='cargoUsedSpace',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrier',
            name='fuelLevel',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='carrier',
            name='reserveBalance',
            field=models.BigIntegerField(default=0),
        ),
    ]
