# Generated by Django 4.1.6 on 2023-03-28 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0004_carrier_allownotorious_carrier_availablebalance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='fuelLevel',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
