# Generated by Django 4.0.5 on 2023-01-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0005_carrier_previouslocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='departureTime',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='nextDestination',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='nextDestinationTime',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='nextLocation',
        ),
    ]
