# Generated by Django 4.0.5 on 2023-01-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0006_remove_carrier_departuretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='dockingAccess',
            field=models.CharField(choices=[('all', 'All'), ('none', 'None'), ('friends', 'Friends'), ('squadron', 'Squadron'), ('squadronfriends', 'Squadron & Friends')], default='all', max_length=255),
        ),
    ]
