# Generated by Django 4.1.6 on 2023-02-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0008_carrierservice_label_alter_carrierservice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='hasOwnWebsite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrier',
            name='imageURL',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
