# Generated by Django 4.1.6 on 2023-02-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0009_carrier_hasownwebsite_carrier_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrier',
            old_name='hasOwnWebsite',
            new_name='isFlagship',
        ),
    ]
