# Generated by Django 4.1.6 on 2023-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0011_carrier_ownerdiscordid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='services',
            field=models.ManyToManyField(blank=True, to='carriers.carrierservice'),
        ),
    ]
