# Generated by Django 4.1.6 on 2023-02-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0012_alter_carrier_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='isFlagship',
        ),
        migrations.AddField(
            model_name='carrier',
            name='category',
            field=models.CharField(choices=[('flagship', 'Flagship'), ('freighter', 'Freighter'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
