# Generated by Django 4.1.6 on 2023-02-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0013_remove_carrier_isflagship_carrier_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='category',
            field=models.CharField(choices=[('flagship', 'Flagship'), ('freighter', 'Freighter'), ('supportvessel', 'Support Vessel'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
