# Generated by Django 4.1.6 on 2023-03-13 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0014_alter_carrier_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrier',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carrierservice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrierservice',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
